<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-13T19:33:49 COT" name="Automation Exercise" finished-at="2023-11-13T19:33:53 COT" duration-ms="3968">
    <groups>
    </groups>
    <test started-at="2023-11-13T19:33:49 COT" name="Automation Test" finished-at="2023-11-13T19:33:53 COT" duration-ms="3968">
      <class name="testCases.TC001_RegisterUser">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:testCases.TC001_RegisterUser@c730b35]" started-at="2023-11-13T19:33:49 COT" name="setUp" finished-at="2023-11-13T19:33:53 COT" duration-ms="3465" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="initializePages()[pri:0, instance:testCases.TC001_RegisterUser@c730b35]" started-at="2023-11-13T19:33:53 COT" name="initializePages" finished-at="2023-11-13T19:33:53 COT" duration-ms="10" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePages -->
        <test-method signature="CheckAccesPage()[pri:1, instance:testCases.TC001_RegisterUser@c730b35]" started-at="2023-11-13T19:33:53 COT" name="CheckAccesPage" finished-at="2023-11-13T19:33:53 COT" duration-ms="47" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1067)
at org.testng.Assert.assertEquals(Assert.java:1031)
at org.testng.Assert.assertEquals(Assert.java:1077)
at testCases.TC001_RegisterUser.CheckAccesPage(TC001_RegisterUser.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckAccesPage -->
        <test-method signature="RegisterNewUser()[pri:2, instance:testCases.TC001_RegisterUser@c730b35]" started-at="2023-11-13T19:33:53 COT" name="RegisterNewUser" finished-at="2023-11-13T19:33:53 COT" depends-on-methods="testCases.TC001_RegisterUser.CheckAccesPage" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testCases.TC001_RegisterUser.RegisterNewUser() on instance testCases.TC001_RegisterUser@c730b35 depends on not successfully finished methods 
[testCases.TC001_RegisterUser.CheckAccesPage() on instance testCases.TC001_RegisterUser@c730b35]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testCases.TC001_RegisterUser.RegisterNewUser() on instance testCases.TC001_RegisterUser@c730b35 depends on not successfully finished methods 
[testCases.TC001_RegisterUser.CheckAccesPage() on instance testCases.TC001_RegisterUser@c730b35]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- RegisterNewUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC001_RegisterUser@c730b35]" started-at="2023-11-13T19:33:53 COT" name="tearDown" finished-at="2023-11-13T19:33:53 COT" duration-ms="93" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC001_RegisterUser -->
    </test> <!-- Automation Test -->
  </suite> <!-- Automation Exercise -->
</testng-results>
